version: 2.1
orbs:
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0
  heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:18-jdk-buster
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd backend
            mvn clean package
  test:
    docker:
      - image: circleci/openjdk:18-jdk-buster
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: |
            cd backend
            mvn test  
  scan:
    docker:
        - image: circleci/openjdk:18-jdk-buster
    environment:
        IMAGE_NAME: jieromu79/cont_integration  
    steps:
        - checkout
        - setup_remote_docker      
        - docker/check
        - run: docker build -t $IMAGE_NAME .
        - snyk/scan: 
            docker-image-name: $IMAGE_NAME
            fail-on-issues: false
            monitor-on-build: true
            project: ${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-app
            severity-threshold: low
            token-variable: SNYK_TOKEN
  build-and-push:
    executor: docker/docker
    environment:
      IMAGE_NAME: jieromu79/cont_integration    
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $IMAGE_NAME
          tag: << pipeline.git.tag >>
      - docker/push:
          image: $IMAGE_NAME
          tag: << pipeline.git.tag >>
  deploy:
      docker:
      - image: circleci/openjdk:18-jdk-buster
      steps:
          - setup_remote_docker      
          - heroku/install
          - checkout
          - run:
              name: Heroku Container Push
              command: | 
                  heroku container:login
                  heroku container:push web -a nutrimateapp
                  heroku container:release web -a nutrimateapp

workflows:
  ci_flow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main

  cicd_flow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - scan:
          requires:
            - test
      - build-and-push:
          requires:
            - scan
      - deploy:
          requires:
            - build-and-push
